// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'features.dart';
import 'muse.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// prefix: "tmp" | "recording" | "session". Empty [record_streams] = all.
/// [started_at_ms] is the Inspect clock origin (EEG timestamps are ms epoch).
Future<void> captureStart({
  required String dir,
  required String prefix,
  required String id,
  required List<String> recordStreams,
  required double startedAtMs,
}) => RustLib.instance.api.crateApiCaptureCaptureStart(
  dir: dir,
  prefix: prefix,
  id: id,
  recordStreams: recordStreams,
  startedAtMs: startedAtMs,
);

Future<void> captureStop() => RustLib.instance.api.crateApiCaptureCaptureStop();

/// Dart posts one JSONL line (no trailing interpretation in Rust).
void captureAppendComputedLine({required List<int> line}) =>
    RustLib.instance.api.crateApiCaptureCaptureAppendComputedLine(line: line);

/// JSONL append (session) or atomic snapshot (monitor); mode from start/prefix.
void captureWriteSidecar({required List<int> json}) =>
    RustLib.instance.api.crateApiCaptureCaptureWriteSidecar(json: json);

/// Tests / Inspect injectors. Live EEG is forked in-process from the forwarder.
void captureAppendEvent({required MuseEventDto event}) =>
    RustLib.instance.api.crateApiCaptureCaptureAppendEvent(event: event);

Future<void> captureFlush() =>
    RustLib.instance.api.crateApiCaptureCaptureFlush();

/// Stream-assemble into `{dir}/{prefix}_{id}.neurofeed`. Deletes temps on success.
/// Returns the destination path. Never returns file bytes.
Future<String> captureAssembleV5({
  required List<int> metadataJson,
  required List<int> thumbnail,
}) => RustLib.instance.api.crateApiCaptureCaptureAssembleV5(
  metadataJson: metadataJson,
  thumbnail: thumbnail,
);

/// Assemble leftover temps with no live session (crash recovery).
Future<String> captureAssembleV5At({
  required String dir,
  required String prefix,
  required String id,
  required List<int> metadataJson,
  required List<int> thumbnail,
}) => RustLib.instance.api.crateApiCaptureCaptureAssembleV5At(
  dir: dir,
  prefix: prefix,
  id: id,
  metadataJson: metadataJson,
  thumbnail: thumbnail,
);

Future<void> captureDiscard() =>
    RustLib.instance.api.crateApiCaptureCaptureDiscard();

List<CaptureFlushEntry> captureFlushIndex() =>
    RustLib.instance.api.crateApiCaptureCaptureFlushIndex();

Int32List captureRecordedChannels() =>
    RustLib.instance.api.crateApiCaptureCaptureRecordedChannels();

BigInt captureDropCount() =>
    RustLib.instance.api.crateApiCaptureCaptureDropCount();

BigInt captureWriteErrors() =>
    RustLib.instance.api.crateApiCaptureCaptureWriteErrors();

bool captureIsActive() => RustLib.instance.api.crateApiCaptureCaptureIsActive();

/// Flush-boundary index entry: elapsed seconds from capture start and the
/// exclusive end offset of the inner zstd frame in the live `.raw`.
class CaptureFlushEntry {
  final double elapsedS;
  final BigInt endOffset;

  const CaptureFlushEntry({required this.elapsedS, required this.endOffset});

  @override
  int get hashCode => elapsedS.hashCode ^ endOffset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CaptureFlushEntry &&
          runtimeType == other.runtimeType &&
          elapsedS == other.elapsedS &&
          endOffset == other.endOffset;
}
