// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`

/// Device configuration — electrode layout, target electrodes for ATR, gate electrodes, enabled features
class DeviceConfig {
  final DeviceKind kind;
  final BigInt channelCount;
  final List<String> electrodeNames;

  /// Electrode indices (0-based) used for ATR reward computation
  final Uint64List targetElectrodes;

  /// Electrode indices required for signal gate (calibration/playing)
  final Uint64List neededElectrodes;

  /// Minimum signal quality (0-100) for "good" electrode
  final double signalGoodThreshold;

  /// Minimum signal quality (0-100) for "critical" electrode (pause threshold)
  final double signalCriticalThreshold;

  /// Features enabled for this device
  final DeviceFeatures features;

  /// Sampling rate in Hz
  final int samplingRate;

  /// Has PPG sensor
  final bool hasPpg;

  /// Has IMU (accel/gyro)
  final bool hasImu;

  const DeviceConfig({
    required this.kind,
    required this.channelCount,
    required this.electrodeNames,
    required this.targetElectrodes,
    required this.neededElectrodes,
    required this.signalGoodThreshold,
    required this.signalCriticalThreshold,
    required this.features,
    required this.samplingRate,
    required this.hasPpg,
    required this.hasImu,
  });

  /// Check if all needed electrodes are good
  Future<bool> allNeededGood({required List<double> quality}) =>
      RustLib.instance.api.crateApiDeviceConfigDeviceConfigAllNeededGood(
        that: this,
        quality: quality,
      );

  /// Get electrode index by name
  Future<BigInt?> electrodeIndex({required String name}) => RustLib.instance.api
      .crateApiDeviceConfigDeviceConfigElectrodeIndex(that: this, name: name);

  /// Get config by kind
  static Future<DeviceConfig> forKind({required DeviceKind kind}) =>
      RustLib.instance.api.crateApiDeviceConfigDeviceConfigForKind(kind: kind);

  /// Check if any needed electrode is usable
  Future<bool> hasNeededElectrode({required List<double> quality}) =>
      RustLib.instance.api.crateApiDeviceConfigDeviceConfigHasNeededElectrode(
        that: this,
        quality: quality,
      );

  /// Check if electrode is usable (above threshold)
  Future<bool> isUsable({
    required List<double> quality,
    required BigInt electrode,
  }) => RustLib.instance.api.crateApiDeviceConfigDeviceConfigIsUsable(
    that: this,
    quality: quality,
    electrode: electrode,
  );

  /// Muse S / Muse 2 (4 EEG, PPG, IMU)
  static Future<DeviceConfig> muse() =>
      RustLib.instance.api.crateApiDeviceConfigDeviceConfigMuse();

  /// Neurosity Crown (8 EEG, no PPG, IMU)
  static Future<DeviceConfig> neurosityCrown() =>
      RustLib.instance.api.crateApiDeviceConfigDeviceConfigNeurosityCrown();

  /// Get target electrode values from a map
  Future<Float32List> targetValues({required Map<BigInt, double> values}) =>
      RustLib.instance.api.crateApiDeviceConfigDeviceConfigTargetValues(
        that: this,
        values: values,
      );

  @override
  int get hashCode =>
      kind.hashCode ^
      channelCount.hashCode ^
      electrodeNames.hashCode ^
      targetElectrodes.hashCode ^
      neededElectrodes.hashCode ^
      signalGoodThreshold.hashCode ^
      signalCriticalThreshold.hashCode ^
      features.hashCode ^
      samplingRate.hashCode ^
      hasPpg.hashCode ^
      hasImu.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceConfig &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          channelCount == other.channelCount &&
          electrodeNames == other.electrodeNames &&
          targetElectrodes == other.targetElectrodes &&
          neededElectrodes == other.neededElectrodes &&
          signalGoodThreshold == other.signalGoodThreshold &&
          signalCriticalThreshold == other.signalCriticalThreshold &&
          features == other.features &&
          samplingRate == other.samplingRate &&
          hasPpg == other.hasPpg &&
          hasImu == other.hasImu;
}

class DeviceFeatures {
  final bool record;
  final bool reward;
  final bool guardrail;
  final bool gesture;

  const DeviceFeatures({
    required this.record,
    required this.reward,
    required this.guardrail,
    required this.gesture,
  });

  static Future<DeviceFeatures> default_() =>
      RustLib.instance.api.crateApiDeviceConfigDeviceFeaturesDefault();

  @override
  int get hashCode =>
      record.hashCode ^ reward.hashCode ^ guardrail.hashCode ^ gesture.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceFeatures &&
          runtimeType == other.runtimeType &&
          record == other.record &&
          reward == other.reward &&
          guardrail == other.guardrail &&
          gesture == other.gesture;
}

/// Headset family (montage / features / Crown-start-refused).
/// Simulation is the `simulate` flag on connect, not a kind.
enum DeviceKind {
  muse,
  neurosity;

  Future<bool> isMuse() =>
      RustLib.instance.api.crateApiDeviceConfigDeviceKindIsMuse(that: this);

  Future<bool> isNeurosity() => RustLib.instance.api
      .crateApiDeviceConfigDeviceKindIsNeurosity(that: this);
}
