// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'edf_export.freezed.dart';

            

            /// Encodes the raw EEG of a `.muse` body as a complete EDF+ file.
///
/// `channel_labels` maps the i16 electrode index to a channel label (e.g.
/// `["TP9", "AF7", "AF8", "TP10"]`); an empty string or out-of-range
/// index means "no data for that electrode". Only electrodes with data
/// are written. Returns an error string when the body has no EEG or the
/// writer rejects the inputs.
Uint8List  encodeEdfExport({required List<int> body , required List<String> channelLabels , required EdfExportParams params }) => RustLib.instance.api.crateApiEdfExportEncodeEdfExport(body: body, channelLabels: channelLabels, params: params);

            @freezed
sealed class EdfExportAnnotation with _$EdfExportAnnotation  {
                
                const factory EdfExportAnnotation({ required  double onsetSeconds, required  String text,}) = _EdfExportAnnotation;
                
                
                
            }

@freezed
sealed class EdfExportParams with _$EdfExportParams  {
                
                const factory EdfExportParams({ required  String patientId, required  String recordingId, required  int year, required  int month, required  int day, required  int hour, required  int minute, required  int second, required  List<EdfExportAnnotation> annotations,}) = _EdfExportParams;
                
                
                
            }
            