// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'session_format.dart';

// These functions are ignored because they are not marked as `pub`: `conditioning`

/// Mains decisions of the current connection so far.
EegConditioning liveEegConditioning() =>
    RustLib.instance.api.crateApiEegConditioningLiveEegConditioning();

/// Condition recorded EEG records (file order) exactly like the live
/// stream. Records keep their order, electrode, timestamp and length.
ConditionedEeg conditionEeg({required List<EegSampleRecord> eeg}) =>
    RustLib.instance.api.crateApiEegConditioningConditionEeg(eeg: eeg);

class ConditionedEeg {
  final List<EegSampleRecord> eeg;
  final EegConditioning conditioning;

  const ConditionedEeg({required this.eeg, required this.conditioning});

  @override
  int get hashCode => eeg.hashCode ^ conditioning.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConditionedEeg &&
          runtimeType == other.runtimeType &&
          eeg == other.eeg &&
          conditioning == other.conditioning;
}

/// Conditioning applied to EEG before quality, bands, features and charts.
class EegConditioning {
  final double highPassHz;
  final double notchQ;
  final List<NotchDecision> decisions;

  const EegConditioning({
    required this.highPassHz,
    required this.notchQ,
    required this.decisions,
  });

  @override
  int get hashCode =>
      highPassHz.hashCode ^ notchQ.hashCode ^ decisions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EegConditioning &&
          runtimeType == other.runtimeType &&
          highPassHz == other.highPassHz &&
          notchQ == other.notchQ &&
          decisions == other.decisions;
}

/// One mains decision: `notch_hz` 50 / 60, or null when no hum was found.
class NotchDecision {
  final double timestampMs;
  final double? notchHz;

  const NotchDecision({required this.timestampMs, this.notchHz});

  @override
  int get hashCode => timestampMs.hashCode ^ notchHz.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotchDecision &&
          runtimeType == other.runtimeType &&
          timestampMs == other.timestampMs &&
          notchHz == other.notchHz;
}
