// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'device_config.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'features.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `active_kind`, `aggregate_band_feature`, `all_known_electrode_names`, `available_on`, `clear_active_kind`, `collect_usable_pads`, `crown_quality`, `default_electrode_names`, `enabled_ids`, `is_enabled`, `is_neurosity`, `pad_quality_from_std_and_noise`, `registry`, `relative`, `resolved_electrode_indices`, `resolved_electrode_names`, `sample_std`, `set_active_kind`, `set_crown_quality`, `spec_by_id`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ChannelBands`, `EegRing`, `Registry`, `Spec`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`, `default`, `default`, `extend`, `new`, `quality`

/// Sync Rust; FRB 2.11.1 exposes a Dart `Future` (not `#[frb(sync)]`).
Future<List<FeatureInfo>> availableFeatures({required DeviceKind kind}) =>
    RustLib.instance.api.crateApiFeaturesAvailableFeatures(kind: kind);

/// Replace-set. Unknown / unavailable-on-active-kind ids → Err.
/// Empty vec unsubscribes all subscribed features. No headset → store the set.
Future<void> setEnabledFeatures({required List<String> ids}) =>
    RustLib.instance.api.crateApiFeaturesSetEnabledFeatures(ids: ids);

/// Optional override; names, not indices. Empty names reset to default.
Future<void> setFeatureElectrodes({
  required String id,
  required List<String> names,
}) => RustLib.instance.api.crateApiFeaturesSetFeatureElectrodes(
  id: id,
  names: names,
);

@freezed
sealed class FeatureDto with _$FeatureDto {
  const factory FeatureDto({
    required String id,
    required double timestamp,
    required double value,
  }) = _FeatureDto;
}

@freezed
sealed class FeatureInfo with _$FeatureInfo {
  const factory FeatureInfo({
    required String id,
    required FeatureSource source,
    required List<FeatureLane> usableFor,
    required List<String> defaultElectrodes,
    required double nativeRateHz,
    required bool available,
    String? unavailableReason,
  }) = _FeatureInfo;
}

enum FeatureLane { reward, guard }

enum FeatureSource { band, ai, device }
