// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Resample one channel from `from_hz` to `to_hz` with rubato's synchronous
/// FFT resampler (Blackman-Harris anti-alias low-pass below the lower
/// Nyquist). Startup delay is trimmed; output length ≈ `len * to / from`.
Float64List resampleEeg({
  required List<double> samples,
  required int fromHz,
  required int toHz,
}) => RustLib.instance.api.crateApiImportDspResampleEeg(
  samples: samples,
  fromHz: fromHz,
  toHz: toHz,
);

/// Band powers for each full 1 s chunk of 256 Hz EEG, 8 values per second:
/// `[delta, theta, alpha, beta, gamma, peak_alpha_hz, peak_alpha_power,
/// line_noise_ratio]` — identical to the live band records.
Float64List eegSecondBands({required List<double> samples}) =>
    RustLib.instance.api.crateApiImportDspEegSecondBands(samples: samples);
