// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'muse.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `compute_bands`, `map_event`, `map_imu`, `spawn_event_forwarder`

/// Scan for nearby Muse devices for `timeout_secs` seconds and return what was
/// found. Results are **merged** into the existing device cache so that the UI
/// can call `scan` repeatedly in short chunks without losing previously
/// discovered peripherals (which `connect` needs via `MuseDevice`).
Future<List<DeviceInfo>> scan({BigInt? timeoutSecs}) =>
    RustLib.instance.api.crateApiMuseScan(timeoutSecs: timeoutSecs);

/// Connect to a previously discovered device by its BLE id and begin streaming.
/// Returns the connection status on success.
///
/// The entire operation is guarded by an overall timeout so the caller never
/// waits more than ≈18 s.  Inside, each BLE step already has its own shorter
/// timeout (10 s connect, 15 s discover services, 8 s startup commands).
Future<ConnectionStatus> connect({required String deviceId}) =>
    RustLib.instance.api.crateApiMuseConnect(deviceId: deviceId);

/// Disconnect from the active device, if any.
///
/// Takes the active connection and immediately clears `guard.events` so the
/// event forwarder stops waiting.  Then sends the BLE disconnect command and
/// fires `Disconnected` through the Dart sink directly — the UI updates
/// straight away instead of waiting for the disconnect-watcher event (which
/// can be delayed on some BLE stacks).
Future<void> disconnect() => RustLib.instance.api.crateApiMuseDisconnect();

/// Current connection status (used on app launch to restore UI state).
Future<ConnectionStatus> getStatus() =>
    RustLib.instance.api.crateApiMuseGetStatus();

/// Returns `true` if a connection is currently active. The Rust side clears
/// this as soon as muse-rs reports a disconnect, so it tracks the real link
/// state closely enough for the UI.
Future<bool> isConnected() => RustLib.instance.api.crateApiMuseIsConnected();

/// Subscribe to the live event stream from the connected headset.
///
/// Call this once at startup. It returns a Dart `Stream<MuseEventDto>` that
/// receives every event emitted by muse-rs for the active (or future)
/// connection. The Rust side forwards events into the provided `StreamSink`.
Stream<MuseEventDto> subscribeEvents() =>
    RustLib.instance.api.crateApiMuseSubscribeEvents();

/// Band power estimates for a single electrode.
/// Bands: [delta, theta, alpha, beta, gamma] in µV²/Hz.
@freezed
sealed class BandsDto with _$BandsDto {
  const factory BandsDto({
    required int electrode,
    required double timestamp,
    required double delta,
    required double theta,
    required double alpha,
    required double beta,
    required double gamma,
  }) = _BandsDto;
}

/// Connection / link status reported to the UI.
@freezed
sealed class ConnectionStatus with _$ConnectionStatus {
  const ConnectionStatus._();
  const factory ConnectionStatus({
    required bool connected,
    required String name,
    required String id,
    required String firmware,
  }) = _ConnectionStatus;
  static Future<ConnectionStatus> default_() =>
      RustLib.instance.api.crateApiMuseConnectionStatusDefault();
}

/// A parsed control/status JSON response from the headset.
@freezed
sealed class ControlDto with _$ControlDto {
  const factory ControlDto({
    required String raw,
    required Map<String, String> fields,
  }) = _ControlDto;
}

/// A Muse device discovered during a scan.
@freezed
sealed class DeviceInfo with _$DeviceInfo {
  const factory DeviceInfo({required String name, required String id}) =
      _DeviceInfo;
}

/// An EEG sample batch for a single electrode channel.
@freezed
sealed class EegDto with _$EegDto {
  const factory EegDto({
    required int index,
    required int electrode,
    required double timestamp,
    required Float64List samples,
  }) = _EegDto;
}

/// A batch of inertial measurements.
@freezed
sealed class ImuDto with _$ImuDto {
  const factory ImuDto({
    required int sequenceId,
    required List<XyzDto> samples,
  }) = _ImuDto;
}

@freezed
sealed class MuseEventDto with _$MuseEventDto {
  const MuseEventDto._();

  const factory MuseEventDto.connected(String field0) = MuseEventDto_Connected;
  const factory MuseEventDto.disconnected() = MuseEventDto_Disconnected;
  const factory MuseEventDto.eeg(EegDto field0) = MuseEventDto_Eeg;
  const factory MuseEventDto.bands(BandsDto field0) = MuseEventDto_Bands;
  const factory MuseEventDto.ppg(PpgDto field0) = MuseEventDto_Ppg;
  const factory MuseEventDto.telemetry(TelemetrySnapshot field0) =
      MuseEventDto_Telemetry;
  const factory MuseEventDto.accelerometer(ImuDto field0) =
      MuseEventDto_Accelerometer;
  const factory MuseEventDto.gyroscope(ImuDto field0) = MuseEventDto_Gyroscope;
  const factory MuseEventDto.control(ControlDto field0) = MuseEventDto_Control;
}

/// A PPG (optical) reading for one channel.
@freezed
sealed class PpgDto with _$PpgDto {
  const factory PpgDto({
    required int index,
    required int channel,
    required double timestamp,
    required Float64List samples,
  }) = _PpgDto;
}

/// Telemetry snapshot (battery etc.) surfaced in the status bar.
@freezed
sealed class TelemetrySnapshot with _$TelemetrySnapshot {
  const TelemetrySnapshot._();
  const factory TelemetrySnapshot({
    required double batteryLevel,
    required double fuelGaugeVoltage,
    required int temperature,
  }) = _TelemetrySnapshot;
  static Future<TelemetrySnapshot> default_() =>
      RustLib.instance.api.crateApiMuseTelemetrySnapshotDefault();
}

/// A 3-axis inertial measurement.
@freezed
sealed class XyzDto with _$XyzDto {
  const factory XyzDto({
    required double x,
    required double y,
    required double z,
  }) = _XyzDto;
}
