// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `handle_band`, `handle_battery`, `handle_osc_message`, `handle_osc_packet`, `handle_raw_eeg`, `handle_signal_quality`, `now_ms`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BandAccumulator`, `CrownOscHandle`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `connect_crown_osc`, `start_crown_osc_receiver`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`, `disconnect`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< JoinHandle < () >>>
abstract class JoinHandle implements RustOpaqueInterface {}
