// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Load a model of [kind] (`reve_base` | `luna_base` | `luna_large`) from
/// [model_dir] (must contain `config.json` and `model.safetensors`) and keep
/// it ready for scoring. Returns a description of the loaded model (inference
/// runs on CPU). Re-loads replace any prior model.
Future<String> modelLoad({required String modelDir, required String kind}) =>
    RustLib.instance.api.crateApiReveModelLoad(modelDir: modelDir, kind: kind);

/// Drop the loaded model and free its memory.
Future<void> modelUnload() => RustLib.instance.api.crateApiReveModelUnload();

/// Whether a model is currently loaded.
Future<bool> modelLoaded() => RustLib.instance.api.crateApiReveModelLoaded();

/// JSON content of the app-generated `config.json` for [kind]. The app writes
/// this file next to the weights so the loader can describe the graph without
/// depending on the Hub's own (sometimes partial) config.
Future<String> modelConfigJson({required String kind}) =>
    RustLib.instance.api.crateApiReveModelConfigJson(kind: kind);
