// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'features.dart';
import 'muse.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'session_format.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `copy_all`, `copy_file_range`, `crc32`, `encode_imu`, `f32`, `f64`, `file_len`, `finished`, `i16`, `new`, `now_secs`, `parse_computed_jsonl`, `parse_records`, `push_f32`, `push_f64`, `push_i16`, `push_u16`, `push_u32`, `read_file_range`, `skip`, `u16`, `u8`, `v5_header_bytes`, `zstd_compress_bytes`, `zstd_compress_file_or_empty`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RecordParser`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// The 12-byte header that prefixes a raw body.
Uint8List sessionHeaderBytes() =>
    RustLib.instance.api.crateApiSessionFormatSessionHeaderBytes();

/// Encode a single Muse event into its record slice (tag + payload). Events
/// that carry no recording data (Connected / Disconnected / Control) produce an
/// empty vector.
Uint8List encodeSessionEvent({required MuseEventDto event}) =>
    RustLib.instance.api.crateApiSessionFormatEncodeSessionEvent(event: event);

/// Assemble the compressed frame for a batch of already-encoded records:
/// `[u32 LE compressed length][zstd frame]`. On compression failure the raw
/// record bytes are stored uncompressed so a session never silently loses data
/// (mirrors the old `compressBlock` fallback in the Dart recorder).
Uint8List sessionFrameBytes({required List<int> data}) =>
    RustLib.instance.api.crateApiSessionFormatSessionFrameBytes(data: data);

/// Decode a full raw body (header + frames) into structured records.
SessionData sessionParseBody({required List<int> bytes}) =>
    RustLib.instance.api.crateApiSessionFormatSessionParseBody(bytes: bytes);

/// Encode a v5 container: header + thumbnail + metadata(zstd) + computed(zstd)
/// + raw body copy. The raw section is a byte-for-byte copy of [raw_body]
/// (already inner-framed). Small fixtures only; keepable captures use
/// [container_encode_v5_to_path].
Uint8List containerEncodeV5({
  required List<int> thumbnail,
  required List<int> metadataJson,
  required List<ComputedFrame> computedFrames,
  required List<int> rawBody,
}) => RustLib.instance.api.crateApiSessionFormatContainerEncodeV5(
  thumbnail: thumbnail,
  metadataJson: metadataJson,
  computedFrames: computedFrames,
  rawBody: rawBody,
);

/// File-to-file assemble. Copies [raw_path] into the raw section (no outer
/// zstd). Empty [computed_jsonl_path] or [raw_path] yields an empty section.
/// Returns [dest_path].
Future<String> containerEncodeV5ToPath({
  required String destPath,
  required List<int> thumbnail,
  required List<int> metadataJson,
  required String computedJsonlPath,
  required String rawPath,
}) => RustLib.instance.api.crateApiSessionFormatContainerEncodeV5ToPath(
  destPath: destPath,
  thumbnail: thumbnail,
  metadataJson: metadataJson,
  computedJsonlPath: computedJsonlPath,
  rawPath: rawPath,
);

/// Rewrite metadata (and optional thumbnail), copying computed and raw
/// sections as opaque bytes. Empty [thumbnail] copies the source thumbnail.
/// Returns [dest_path].
Future<String> v5RewriteHeadToPath({
  required String srcPath,
  required String destPath,
  required List<int> metadataJson,
  required List<int> thumbnail,
}) => RustLib.instance.api.crateApiSessionFormatV5RewriteHeadToPath(
  srcPath: srcPath,
  destPath: destPath,
  metadataJson: metadataJson,
  thumbnail: thumbnail,
);

/// Parse v5 head from a file without reading the raw section.
Future<V5ParsedHead> v5ParseHeadFromPath({required String path}) =>
    RustLib.instance.api.crateApiSessionFormatV5ParseHeadFromPath(path: path);

/// Extract computed frames from a file without reading the raw section.
Future<List<ComputedFrame>> v5ExtractComputedFromPath({required String path}) =>
    RustLib.instance.api.crateApiSessionFormatV5ExtractComputedFromPath(
      path: path,
    );

/// Parse v5 header (first 68 bytes).
V5Header v5ParseHeader({required List<int> bytes}) =>
    RustLib.instance.api.crateApiSessionFormatV5ParseHeader(bytes: bytes);

/// Parse v5 head (header + thumbnail + metadata).
V5ParsedHead v5ParseHead({required List<int> bytes}) =>
    RustLib.instance.api.crateApiSessionFormatV5ParseHead(bytes: bytes);

/// Extract computed section (decompressed JSON lines).
List<ComputedFrame> v5ExtractComputed({required List<int> bytes}) =>
    RustLib.instance.api.crateApiSessionFormatV5ExtractComputed(bytes: bytes);

/// Extract the raw section as the framed body (no outer zstd).
Uint8List v5ExtractRaw({required List<int> bytes}) =>
    RustLib.instance.api.crateApiSessionFormatV5ExtractRaw(bytes: bytes);

@freezed
sealed class BandsRecord with _$BandsRecord {
  const factory BandsRecord({
    required double timestamp,
    required int electrode,
    required double delta,
    required double theta,
    required double alpha,
    required double beta,
    required double gamma,
  }) = _BandsRecord;
}

/// Computed frame at 1 Hz for training/export.
/// All bands are absolute power (not relative).
@freezed
sealed class ComputedFrame with _$ComputedFrame {
  const ComputedFrame._();
  const factory ComputedFrame({
    required double t,
    required List<Float32List> bands,
    double? pulse,
    double? movement,
    PeakAlphaInfo? peakAlpha,
    double? spo2,
    required Float32List lineNoise,
    required Uint8List signalQuality,
    required GuardrailInfo guardrail,
    required FeedbackInfo feedback,
    required List<String> gestures,
  }) = _ComputedFrame;

  /// Decode from JSON bytes.
  static Future<ComputedFrame?> fromJsonBytes({required List<int> bytes}) =>
      RustLib.instance.api.crateApiSessionFormatComputedFrameFromJsonBytes(
        bytes: bytes,
      );

  /// Encode to JSON bytes (for zstd compression).
  Future<Uint8List> toJsonBytes() => RustLib.instance.api
      .crateApiSessionFormatComputedFrameToJsonBytes(that: this);
}

/// One raw EEG packet: per-sample values are in µV, `timestamp` is the
/// wall-clock ms epoch of the FIRST sample, and consecutive samples are
/// `rate` apart (nominal 256 Hz on Muse headsets).
@freezed
sealed class EegSampleRecord with _$EegSampleRecord {
  const factory EegSampleRecord({
    required double timestamp,
    required int electrode,
    required Float32List samples,
  }) = _EegSampleRecord;
}

/// Feedback (ATR) info.
@freezed
sealed class FeedbackInfo with _$FeedbackInfo {
  const factory FeedbackInfo({
    required double ratio,
    required double threshold,
    required bool inTarget,
    required double pct,
  }) = _FeedbackInfo;
}

/// Guardrail (AI drowsiness) info.
@freezed
sealed class GuardrailInfo with _$GuardrailInfo {
  const factory GuardrailInfo({
    required double sleepDir,
    required double clarity,
    required bool warning,
    required double delta,
  }) = _GuardrailInfo;
}

@freezed
sealed class MovementRecord with _$MovementRecord {
  const factory MovementRecord({
    required double timestamp,
    required double score,
  }) = _MovementRecord;
}

/// Peak alpha frequency and power.
@freezed
sealed class PeakAlphaInfo with _$PeakAlphaInfo {
  const factory PeakAlphaInfo({required double freq, required double power}) =
      _PeakAlphaInfo;
}

@freezed
sealed class PeakAlphaRecord with _$PeakAlphaRecord {
  const factory PeakAlphaRecord({
    required double timestamp,
    required double frequency,
    required double power,
  }) = _PeakAlphaRecord;
}

@freezed
sealed class PulseRecord with _$PulseRecord {
  const factory PulseRecord({
    required double timestamp,
    required double bpm,
    required double confidence,
  }) = _PulseRecord;
}

/// Decoded records of a raw body.
@freezed
sealed class SessionData with _$SessionData {
  const factory SessionData({
    required List<BandsRecord> bands,
    required List<PulseRecord> pulses,
    required List<SpO2Record> spo2S,
    required List<MovementRecord> movements,
    required List<PeakAlphaRecord> peakAlphas,
    required BigInt eegSamples,
    required List<EegSampleRecord> eeg,
  }) = _SessionData;
}

@freezed
sealed class SpO2Record with _$SpO2Record {
  const factory SpO2Record({
    required double timestamp,
    required double spo2,
    required double confidence,
  }) = _SpO2Record;
}

/// v5 container header with fixed 68-byte layout.
/// raw_length is not stored; compute as file_size - raw_offset.
@freezed
sealed class V5Header with _$V5Header {
  const factory V5Header({
    required BigInt thumbnailOffset,
    required BigInt thumbnailLength,
    required BigInt metadataOffset,
    required BigInt metadataLength,
    required BigInt computedOffset,
    required BigInt computedLength,
    required BigInt rawOffset,
  }) = _V5Header;
}

/// Parsed v5 head - header + thumbnail + metadata (decompressed).
@freezed
sealed class V5ParsedHead with _$V5ParsedHead {
  const factory V5ParsedHead({
    required V5Header header,
    required Uint8List thumbnail,
    required Uint8List metadataJson,
  }) = _V5ParsedHead;
}
