// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'muse.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'session_format.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `encode_imu`, `f32`, `f64`, `finished`, `i16`, `local_image_length`, `new`, `now_secs`, `parse_records`, `push_f32`, `push_f64`, `push_i16`, `push_u16`, `push_u32`, `skip`, `u16`, `u8`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RecordParser`

/// The 12-byte header that prefixes a `.muse` body.
Uint8List sessionHeaderBytes() =>
    RustLib.instance.api.crateApiSessionFormatSessionHeaderBytes();

/// Encode a single Muse event into its record slice (tag + payload). Events
/// that carry no recording data (Connected / Disconnected / Control) produce an
/// empty vector.
Uint8List encodeSessionEvent({required MuseEventDto event}) =>
    RustLib.instance.api.crateApiSessionFormatEncodeSessionEvent(event: event);

/// Assemble the compressed frame for a batch of already-encoded records:
/// `[u32 LE compressed length][zstd frame]`. On compression failure the raw
/// record bytes are stored uncompressed so a session never silently loses data
/// (mirrors the old `compressBlock` fallback in the Dart recorder).
Uint8List sessionFrameBytes({required List<int> data}) =>
    RustLib.instance.api.crateApiSessionFormatSessionFrameBytes(data: data);

/// Decode a full `.muse` body (header + frames) into structured records.
Future<SessionData> sessionParseBody({required List<int> bytes}) =>
    RustLib.instance.api.crateApiSessionFormatSessionParseBody(bytes: bytes);

/// FFI getter for [CONTAINER_HEAD_READ_LIMIT] so Dart never hardcodes it.
BigInt containerHeadReadLimit() =>
    RustLib.instance.api.crateApiSessionFormatContainerHeadReadLimit();

/// Assemble a single `.muse.feedback` file: PNG first, then json, then body.
Uint8List containerEncodeBytes({
  required List<int> png,
  required List<int> json,
  required List<int> body,
}) => RustLib.instance.api.crateApiSessionFormatContainerEncodeBytes(
  png: png,
  json: json,
  body: body,
);

/// Parse the head of a container (PNG + json). `body_len` is resolved only when
/// the full body is present in [bytes]; a partial (prefix) read leaves it None.
ContainerHead containerParseHeadBytes({required List<int> bytes}) => RustLib
    .instance
    .api
    .crateApiSessionFormatContainerParseHeadBytes(bytes: bytes);

/// Extract the full frame body from a complete container [bytes], or None when
/// the body length is absent (head-only read).
Uint8List? containerExtractBodyBytes({required List<int> bytes}) => RustLib
    .instance
    .api
    .crateApiSessionFormatContainerExtractBodyBytes(bytes: bytes);

@freezed
sealed class BandsRecord with _$BandsRecord {
  const factory BandsRecord({
    required double timestamp,
    required int electrode,
    required double delta,
    required double theta,
    required double alpha,
    required double beta,
    required double gamma,
  }) = _BandsRecord;
}

/// Decoded head fields of a container.
@freezed
sealed class ContainerHead with _$ContainerHead {
  const factory ContainerHead({
    required Uint8List pngBytes,
    required Uint8List jsonBytes,
    int? bodyLen,
  }) = _ContainerHead;
}

/// One raw EEG packet: per-sample values are in µV, `timestamp` is the
/// wall-clock ms epoch of the FIRST sample, and consecutive samples are
/// `rate` apart (nominal 256 Hz on Muse headsets).
@freezed
sealed class EegSampleRecord with _$EegSampleRecord {
  const factory EegSampleRecord({
    required double timestamp,
    required int electrode,
    required Float32List samples,
  }) = _EegSampleRecord;
}

@freezed
sealed class MovementRecord with _$MovementRecord {
  const factory MovementRecord({
    required double timestamp,
    required double score,
  }) = _MovementRecord;
}

@freezed
sealed class PeakAlphaRecord with _$PeakAlphaRecord {
  const factory PeakAlphaRecord({
    required double timestamp,
    required double frequency,
    required double power,
  }) = _PeakAlphaRecord;
}

@freezed
sealed class PulseRecord with _$PulseRecord {
  const factory PulseRecord({
    required double timestamp,
    required double bpm,
    required double confidence,
  }) = _PulseRecord;
}

/// Decoded records of a `.muse` body.
@freezed
sealed class SessionData with _$SessionData {
  const factory SessionData({
    required List<BandsRecord> bands,
    required List<PulseRecord> pulses,
    required List<SpO2Record> spo2S,
    required List<MovementRecord> movements,
    required List<PeakAlphaRecord> peakAlphas,
    required BigInt eegSamples,
    required List<EegSampleRecord> eeg,
  }) = _SessionData;
}

@freezed
sealed class SpO2Record with _$SpO2Record {
  const factory SpO2Record({
    required double timestamp,
    required double spo2,
    required double confidence,
  }) = _SpO2Record;
}
