// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'device_config.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `eeg_sample`, `now_ms`, `ppg_sample`, `run_eeg`, `run_imu`, `run_ppg`, `run_telemetry`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DeviceSimulator`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `spawn_simulator`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `new`, `start`, `stop`

/// Connected name and firmware for a `sim:*` catalog id.
/// Unknown ids fall back to Muse S / Crown from [kind].
Future<(String, String)> simulatedIdentity({
  required String deviceId,
  required DeviceKind kind,
}) => RustLib.instance.api.crateApiSimulatorSimulatedIdentity(
  deviceId: deviceId,
  kind: kind,
);
